jobs:
  main:
    image: node:16
    requires: [ ~pr, ~pr:pr-comment, ~commit ]
    steps:
      - markdown: meta set meta.summary.markdown "this markdown comment is **bold** and *italic*"
      - coverage: meta set meta.summary.coverage "Coverage increased by 15%"
  main-2:
    image: node:16
    requires: [ ~pr, ~commit ]
    steps:
      - markdown: meta set meta.summary.markdown "this markdown comment is **bold** and *italic*"
      - coverage: meta set meta.summary.coverage "Coverage increased by 15%"
