annotations:
  screwdriver.cd/chainPR: true
 
shared:
  image: node:16
 
jobs:
  build1:
    requires: [ ~commit, ~pr ]
    steps:
       - metaget: meta get hello
       - metaset: meta set hello "Hello build1"
  build2:
    requires: [ build1 ]
    steps:
       - metaget: meta get hello
       - metaset: meta set hello "Hello build2"
       - metaget2: meta get hello2
       - metaset2: meta set hello2 "Hello build2"
  build3:
    requires: [ build1 ]
    parameters:
      number:
        value: "1"
    steps:
       - metaget: meta get hello
       - metaset: meta set hello "Hello build3"
       - metaget2: meta get hello3
       - metaset2: meta set hello3 "Hello build3"
       - fail:  |
          if test "$(meta get parameters.number.value)" == "1"; then exit 1; fi;
  build4:
    requires: [ build2, build3 ]
    steps:
       - metaget: meta get hello
       - metaset: meta set hello "Hello build4"
       - metaget2: meta get hello2
       - metaget3: meta get hello3
       - metaget4: meta get hello4
       - metaset4: meta set hello4 "Hello build4"
