annotations:
  screwdriver.cd/useDeployKey: true
shared:
  image: node:16
 
jobs:
  b:
    requires: [ ~commit, ~sd@13168:a ]
    steps:
      - show: echo b
  c:
    requires: [ ~commit, ~sd@13168:a ]
    steps:
      - show: echo c
  f:
    requires: [ ~sd@13168:d, ~sd@13168:e ]
    steps:
      - show: echo f
