shared:
  image: node:16
 
jobs:
  a:
    requires: [ ~commit ]
    steps:
      - show: echo a
  d:
    requires: [ ~sd@13169:b, ~sd@13169:c ]
    steps:
      - show: echo d
  e:
    requires: [ ~sd@13169:b, ~sd@13169:c ]
    steps:
      - show: echo e
