annotations:
  screwdriver.cd/chainPR: true
jobs:
  job1:
    requires: [ ~pr, ~commit ]
    image: node:16
    steps:
      - main: echo hoge
  not-start:
    annotations:
      screwdriver.cd/jobDisabledByDefault: true
    requires: [ ~pr, ~commit ]
    image: node:16
    steps:
      - main: echo hoge
  not-start-2:
    annotations:
      screwdriver.cd/jobDisabledByDefault: true
    requires: [ ~pr, ~commit ]
    image: node:16
    steps:
      - main: echo hoge
