shared:
  image: node:14
  settings:
    slack:
      channels:
        - slack-test1
      statuses:
        - SUCCESS
        - FAILURE
        - QUEUED
      minimized: false
jobs:
  dogs:
    requires: [ ~pr, ~commit ]
    steps:
      - echo "a"
      - which a
