shared:
  image: node:18

jobs:
  main:
    requires: [ ~commit ]
    steps:
      - echo "This is main job"
      - cat aaa/t.txt
  main-pr:
    requires: [ ~pr ]
    steps:
      - echo "This is main-pr job"
      - cat aaa/t.txt
  staging:
    requires: [ ~commit:branch-specific-branch ]
    steps:
      - echo "This is staging job"
      - cat aaa/t.txt
  staging-pr:
    requires: [ ~pr:branch-specific-branch ]
    steps:
      - echo "This is staging-pr job"
      - cat aaa/t.txt
  detached:
    steps:
      - echo "This is detached job"
      - cat aaa/t.txt
  detached2:
    steps:
      - echo "This is detached2 job"
      - cat aaa/t.txt
