shared:
  image: node:18

jobs:
  test:
    requires: [ ~pr, ~commit ]
    steps:
      - install: echo b
  test-2:
    template: sd/noop@latest
    requires: [ ~pr, ~commit ]
  test-3:
    requires: [ ~pr, ~commit ]
    steps:
      - install: echo a
