shared:
  image: node:16
 
jobs:
  build1:
    requires: [ ~commit, ~pr ]
    steps:
      - hello: echo "Hello build1"
  build2:
    requires: [ ~commit, ~pr ]
    steps:
      - hello: echo "Hello build2"
