shared:
  image: node14:latest
    
jobs:
  A:
    requires: [ ~commit ]
    steps:
      - show: echo 'A'
  B:
    requires: [ ~commit ]
    steps:
      - show: echo 'B'
      - sleep: sleep 300
  C:
    requires: [ ~commit ]
    steps:
      - show: echo 'C'
  D:
    requires: [ ~A, B, C]
    steps:
      - show: echo 'D'
      - sleep: sleep 100
