shared:
  image: node:18

jobs:
  first:
    requires: [ ~commit ]
    steps:
      - test: echo 'foo'
  or-join:
    requires: [ ~sd@12752:sub1 ]
    steps:
      - test: echo 'foo'
  and-join:
    requires: [ sd@12752:sub1, sd@12752:sub2 ]
    steps:
      - test: echo 'foo'
